version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "80:80"
    volumes:
     - ./app:/var/www/html
    environment:
     - PORT=80
     - CLEARDB_DATABASE_URL=mysql://admin:test@db/database

  db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
    ports:
      - "8889:3306"

  webpack:
    build:
      context: .
      dockerfile: Dockerfile-webpack
    volumes:
      - .:/code
      - /code/node_modules




